import { test, expect } from '@playwright/test'

// Local, read-only product review. No gigs, accounts or reviews are created.
test.beforeEach(async ({ baseURL }) => {
  expect(baseURL, 'Design review must only run on the local preview').toMatch(/^http:\/\/127\.0\.0\.1:/)
})

test('editorial home, carousel controls, calculator, category routing and responsive layout', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /Your thing/ })).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  await expect(page.locator('.story-frame.is-active img')).toHaveJSProperty('naturalWidth', 1536)
  await page.screenshot({ path: process.env.REVIEW_OUTPUT + '/sidegigs-desktop.png', fullPage: true })
  await page.screenshot({ path: process.env.REVIEW_OUTPUT + '/sidegigs-hero.png' })
  await page.getByRole('button', { name: 'Next worker image' }).click()
  await expect(page.locator('.story-frame.is-active')).toContainText('Make something click.')
  await page.getByRole('button', { name: 'Previous worker image' }).click()
  await expect(page.locator('.story-frame.is-active')).toContainText('An eye for the moment.')
  await expect(page.getByRole('button', { name: 'Play worker slideshow' })).toBeDisabled()
  await page.getByRole('button', { name: 'I need a hand' }).click()
  await expect(page.getByRole('heading', { name: 'Tell us what needs doing.' })).toBeVisible()
  await page.getByRole('button', { name: /R1\s?000/, exact: true }).click()
  await expect(page.locator('.fee-total')).toContainText('1')
  await expect(page.locator('.fee-total dd')).toHaveText(/R1\s?150/)
  await page.getByRole('button', { name: 'R500', exact: true }).click()
  await expect(page.locator('.fee-total dd')).toHaveText('R575')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await expect(page.getByRole('heading', { name: /Your thing/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: process.env.REVIEW_OUTPUT + '/sidegigs-mobile.png', fullPage: true })
  await page.locator('.category-tile').filter({ hasText: 'Gardening' }).click()
  await expect(page).toHaveURL(/discover\?category=gardening/)
  await expect(page.getByRole('button', { name: 'Gardening', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('heading', { name: 'Good work. Close to home.' })).toBeVisible()
  await page.screenshot({ path: process.env.REVIEW_OUTPUT + '/sidegigs-discover-mobile.png', fullPage: true })
  await page.goto('/signup?role=customer&next=%2Fgigs%2Fnew')
  await expect(page.getByRole('radio', { name: /I need help/ })).toBeChecked()
  expect(errors).toEqual([])
})

test('posting preview explains pricing and next steps without publishing', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/login?next=%2Fgigs%2Fnew')
  await page.getByRole('button', { name: /Try as Thandi/ }).click()
  await expect(page).toHaveURL(/gigs\/new/)
  await page.getByLabel('What do you need done?').fill('Help refresh my courtyard garden')
  await page.getByRole('button', { name: /Gardening/ }).click()
  await page.getByLabel('Describe the work').fill('Trim a small hedge and plant six herbs in existing pots. Please bring gardening gloves and hand tools.')
  await page.getByLabel('What will the worker earn?').fill('500')
  await expect(page.getByLabel('Price breakdown')).toContainText('R575')
  await expect(page.getByText(/You won’t be charged/)).toBeVisible()
  await page.screenshot({ path: process.env.REVIEW_OUTPUT + '/sidegigs-post-task.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: process.env.REVIEW_OUTPUT + '/sidegigs-post-task-mobile.png', fullPage: true })
})
