// Generates the SideGigs post-quantum key material.
// - Writes PUBLIC keys to src/lib/pq-public-keys.ts (safe to commit).
// - Writes SECRET seeds to .env.pq (gitignored) — copy them into Netlify as secret env vars.
// Usage: npm run keys:generate
import { writeFileSync, existsSync } from 'node:fs'
import { createHash, randomBytes } from 'node:crypto'
import { ml_kem768_x25519 } from '@noble/post-quantum/hybrid.js'
import { ml_dsa65 } from '@noble/post-quantum/ml-dsa.js'

if (existsSync('.env.pq') && !process.argv.includes('--force')) {
  console.error('.env.pq already exists. Re-run with --force to rotate keys (existing envelopes will need re-encryption).')
  process.exit(1)
}

const kemSeed = randomBytes(32)
const signSeed = randomBytes(32)
const kem = ml_kem768_x25519.keygen(kemSeed)
const sign = ml_dsa65.keygen(signSeed)

const b64 = (u8) => Buffer.from(u8).toString('base64')
const kid = (u8) => createHash('sha256').update(u8).digest('hex').slice(0, 16)

const publicFile = `// Generated by scripts/generate-pq-keys.mjs — public keys only, safe to commit.
// Secrets live in Netlify env vars PQ_KEM_SECRET_SEED / PQ_SIGN_SEED.
export const KEM_PUBLIC_KEY_B64 =
  '${b64(kem.publicKey)}'
export const KEM_KID = '${kid(kem.publicKey)}'
export const SIGN_PUBLIC_KEY_B64 =
  '${b64(sign.publicKey)}'
export const SIGN_KID = '${kid(sign.publicKey)}'
`
writeFileSync('src/lib/pq-public-keys.ts', publicFile)
writeFileSync('.env.pq', `PQ_KEM_SECRET_SEED=${b64(kemSeed)}\nPQ_SIGN_SEED=${b64(signSeed)}\n`)
console.log('Public keys → src/lib/pq-public-keys.ts')
console.log('Secret seeds → .env.pq (gitignored). Set them as Netlify secret env vars.')
